# Copyright 2026 Julien Bombled
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Configure WSUS server
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: WUServer
    data: "{{ metabaseos_wsus_server }}"
    type: string
  when: metabaseos_wsus_enabled

- name: Enable WSUS status server
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: WUStatusServer
    data: "{{ metabaseos_wsus_server }}"
    type: string
  when: metabaseos_wsus_enabled

- name: Configure WSUS auto-update policy
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: UseWUServer
    data: 1
    type: dword
  when: metabaseos_wsus_enabled

- name: Configure Windows Update auto-install
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: AUOptions
    data: "{{ 4 if metabaseos_wu_auto_install else 3 }}"
    type: dword

- name: Set scheduled install day
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: ScheduledInstallDay
    data: "{{ metabaseos_wu_scheduled_day }}"
    type: dword

- name: Set scheduled install time
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: ScheduledInstallTime
    data: "{{ metabaseos_wu_scheduled_hour }}"
    type: dword
